name: CI

on: push

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.2

    - name: Extract
      shell: bash
      run: |
        curl -Lo SB3UGS_v20.6.3.7z https://github.com/enimaroah/SB3Utility/releases/download/20.6.3/SB3UGS_v20.6.3.7z
        7z x SB3UGS_v20.6.3.7z -osrc/libs/SB3UGS

    - name: Restore
      run: nuget restore src/KKManager.sln

    - name: Build
      run: msbuild src/KKManager.sln /t:build /p:Configuration=Release

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: Test
        path: src/bin
